### ISSUE TITLE
Debug area bugs

### ISSUE THREAD

**Issue by bulantsevajo** [scade-platform/Nimble#215]
1. Can't close debug area if there is active run. Open debug area -> run swift project -> click close button (right top corner)
<img width="1088" alt="Screenshot 2022-09-12 at 12 36 39" src="https://user-images.githubusercontent.com/10060762/189581834-da6750bb-1866-44a9-82d0-f1bd603e7e7f.png">

2. Extra space between project name and buttons. There is no margin between remove button and Nimble corners
<img width="1063" alt="Screenshot 2022-09-12 at 12 36 27" src="https://user-images.githubusercontent.com/10060762/189582305-ac7efc0d-3b43-4f4a-97c1-f7981e980b73.png">

3. Close debug area -> run Swift project. Result: opened errors icon, but should be file icon

<img width="1065" alt="Screenshot 2022-09-12 at 12 36 53" src="https://user-images.githubusercontent.com/10060762/189582509-95b7566f-3abd-4bbc-ad73-514efaf52e6d.png">

4. Close degug view -> click on errors icon. Result: menu opens on full screen
<img width="1069" alt="Screenshot 2022-09-12 at 13 05 36" src="https://user-images.githubusercontent.com/10060762/189584471-9e4cf1a8-eb50-438e-89b4-42cd43a2e608.png">

5. Open/close debug area button doesn't change the color. Attached screen shot how it should be
<img width="95" alt="Screenshot 2022-09-12 at 14 26 42" src="https://user-images.githubusercontent.com/10060762/189596690-fd373b18-062c-4642-98a9-5f5a74792807.png">

**Comment by AlYehorov** [comment]
2: Not reproducible 
5: Not a bug
@bulantsevajo

**Comment by bulantsevajo** [comment]
@AlYehorov also:
6. Close debug view by default
